# cmd pour lancer en dev: docker compose --profile dev up -d
services:
  # -----------------------------
  # Base de données (PostgreSQL)
  # -----------------------------
  postgres:
    image: postgres:15
    container_name: ft_transcendence_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST} 
      POSTGRES_PORT: ${POSTGRES_PORT} 
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks: [internal]

  # -----------------------------
  # Accès à la db en dev (adminer)
  # -----------------------------
  adminer:
    image: adminer:latest
    container_name: ft_transcendence_adminer
    restart: unless-stopped
    profiles: ["dev"]
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - postgres
    networks: [internal]

  # -----------------------------
  # Cache & Temps réel (Redis)
  # -----------------------------
  redis:
    image: redis:7
    container_name: ft_transcendence_redis
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6380:6379"
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    networks: [internal]

  # -----------------------------
  # Backend (NestJS)
  # -----------------------------

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ft_transcendence_backend
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      REDIS_URL: ${REDIS_URL}
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_CACERT: ${VAULT_CACERT}
      VAULT_SKIP_VERIFY: "false"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - .vault-secrets/approle:/run/approle:ro
      - .vault-secrets/vault_certs:/etc/vault/certs:ro
      - .vault-secrets/vault_certs:/etc/vault/certs:ro
    depends_on:
      - postgres
      - redis
    networks: [internal]
    # Command pour le dev (hot reload)
    command: npm run start:dev

  # -----------------------------
  # Vault Hashicorp
  # -----------------------------

  init_vault:
    build:
      context: ./backend/vault/init_service
      dockerfile: Dockerfile
    container_name: vault_fix_perms
    environment:
      LOCAL_UID: ${LOCAL_UID:-1000}
      LOCAL_GID: ${LOCAL_GID:-1000}
    networks: [internal]
    volumes:
      - vault_data:/vault/data
      - .vault-secrets/core:/vault/local-secrets
      - .vault-secrets/approle:/vault/approle
      - .vault-secrets/vault_certs:/certs

  vault:
    build:
      context: ./backend/vault
      dockerfile: Dockerfile
    container_name: ft_transcendence_vault
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    networks: [internal]
    expose:
      - "8200"
    cap_add:
      - IPC_LOCK # Empêche la RAM d'être copiée sur le disque
    depends_on:
      init_vault:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - vault_data:/vault/data
      - .vault-secrets/core:/vault/local-secrets:rw
      - .vault-secrets/approle:/vault/approle:rw
      - .vault-secrets/vault_certs:/etc/vault/certs:ro

  # -----------------------------
  # Frontend (React + Vite)
  # -----------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ft_transcendence_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always
    depends_on:
      - backend
    networks: [internal]

  # -----------------------------
  # Nginx (WAP)
  # -----------------------------
  nginx:
    build:
      context: ./backend/WAP
      dockerfile: Dockerfile
    container_name: ft_transcendence_wap
    environment:
      - PARANOIA=1
      - ANOMALY_INBOUND=10
      - DISABLE_DEFAULT_CONF=1
    ports:
      - "443:443"
      - "81:80"
    depends_on:
      - postgres
      - redis
      - backend
      - frontend
    networks: [internal]

volumes:
  vault_data:
    driver: local
  
#   ./data:/var/lib/postgresql/data

networks:
  internal:
    driver: bridge